import { useVideoPlayer, VideoView } from 'expo-video';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

type Props = {
  visible: boolean;
  videoUrl: string | null;
  dogName: string;
  onClose: () => void;
};

export function VideoPreviewModal({ visible, videoUrl, dogName, onClose }: Props) {
  const player = useVideoPlayer(visible ? videoUrl : null, (p) => {
    p.loop = true;
    p.muted = true;
    p.play();
  });

  if (!videoUrl) return null;

  return (
    <Modal visible={visible} animationType="fade" transparent onRequestClose={onClose}>
      <SafeAreaView style={styles.backdrop} edges={['top', 'bottom']}>
        <View style={styles.card}>
          <View style={styles.headerRow}>
            <Text style={styles.title}>{dogName}&apos;s video</Text>
            <Pressable
              onPress={onClose}
              hitSlop={12}
              style={({ pressed }) => [styles.close, pressed && { opacity: 0.55 }]}
            >
              <Text style={styles.closeText}>✕</Text>
            </Pressable>
          </View>

          <View style={styles.videoFrame}>
            <VideoView
              style={styles.video}
              player={player}
              contentFit="cover"
              allowsFullscreen={false}
              nativeControls={false}
            />
            <View style={styles.aiBadge}>
              <Text style={styles.aiBadgeText}>✨ AI</Text>
            </View>
          </View>

          <Text style={styles.caption}>
            Loops muted on the deck. Generated by Veo 3.1 Lite.
          </Text>

          <Pressable
            style={({ pressed }) => [styles.primaryButton, pressed && { opacity: 0.75 }]}
            onPress={onClose}
          >
            <Text style={styles.primaryText}>Looks great</Text>
          </Pressable>
        </View>
      </SafeAreaView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    padding: 20,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#15151b',
    borderRadius: 24,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: '#2a2a30',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  close: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2a2a30',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  videoFrame: {
    aspectRatio: 1,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#0B0B0F',
    position: 'relative',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  aiBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  aiBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  caption: {
    color: '#9a9aa0',
    fontSize: 13,
    textAlign: 'center',
  },
  primaryButton: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
});
